### ISSUE TITLE
Feature request: add ability to prioritize or add a delay to grabbing the global name.

### ISSUE THREAD

**Issue by ltd** [derekkraan/highlander#5]
At the risk of adding a slight complexity to a great simple library.

I have two use cases where the default behavior is not optimal.

1)  When adding a new machine to the cluster, on startup before other nodes are discovered grabbing the global name will eventually cause a name conflict and possibly unnecessarily kill the existing owner  that has been up for  some time.

2) In a cluster where there are mix of permanent instance and spot instances, I would prefer  permanent instances take priority over the spots.

My initial approach is to call a function in the child module (if defined), during the registration which can add a pause.    If this seems like a sane approach I will submit a pull request when done.

**Comment by derekkraan** [comment]
To solve case 1 I would recommend starting highlander lower in your supervision tree than your prices that is handling discovery and clustering. For the second case, I'm not quite sure what would be a reasonable solution, but perhaps if you solve #1 it won't be as pressing anymore.

It is easy enough to do these things in your own program so I don't see this being accepted as a PR to this library.

**Comment by ltd** [comment]
@derekkraan thanks for the response, and no problem not wanting a PR, as you mentioned there are several way I can solve this.
