### ISSUE TITLE
Use case for Highlander without handle_call etc?

### ISSUE THREAD

**Issue by krns** [derekkraan/highlander#7]
I needed a globally unique process that I can perfectly start with Highlander. So far so good. However, I cannot work with this process:

- I get the pid via `:global.whereis_name({Highlander, Module})`
- and try to call the process via `GenServer.call(pid, atom)`
- I get `... no handle_call/3 clause was provided` by Highlander

Am I missing something or is this not the intention behind Highlander? Thanks in advance :)

**Comment by derekkraan** [comment]
I would suggest starting your process with `name: {:global, "my_global_name}` and using that. Highlander doesn't pass messages to your process.

Closing but feel free to re-open if this doesn't answer your question.
